// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIReact.Models
{
    public partial class Conversation
    {
        public Conversation()
        {
            Messages = new HashSet<Messages>();
        }

        public Guid Id { get; set; }
        public Guid UserId { get; set; }

        public virtual User IdNavigation { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
    }
}