// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIDAL.MySql.Entities
{
    public partial class Availablesize
    {
        public string Id { get; set; }
        public string MenuItemId { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }
    }
}