// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIDAL.MySql.Entities
{
    public partial class Loginlog
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string Ipaddress { get; set; }
        public string Device { get; set; }
        public string CountryCode { get; set; }
        public DateTime CreatedDatetime { get; set; }
        public DateTime UpdateDatetime { get; set; }
    }
}