// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIDAL.MySql.Entities
{
    public partial class Orderdetailtopping
    {
        public string Id { get; set; }
        public string OrderId { get; set; }
        public string OrderDetailId { get; set; }
        public string ToppingId { get; set; }
        public int Value { get; set; }
        public string Memo { get; set; }
        public DateTime CreatedDatetime { get; set; }
        public DateTime UpdateDatetime { get; set; }
    }
}