// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIService.Entities
{
    public partial class Message
    {
        public Message()
        {
            Order = new HashSet<Order>();
        }

        public Guid Id { get; set; }
        public Guid ConversationId { get; set; }
        public string Message1 { get; set; }
        public int OrderId { get; set; }
        public DateTime CreatedDatetime { get; set; }
        public DateTime UpdateDatetime { get; set; }

        public virtual Conversation Conversation { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}