// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIService.Entities
{
    public partial class ToppingStore
    {
        public Guid Id { get; set; }
        public Guid ToppingId { get; set; }
        public int Count { get; set; }
        public DateTime CreatedDatetime { get; set; }
        public DateTime UpdateDatetime { get; set; }

        public virtual Topping Topping { get; set; }
    }
}