// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIService.Entities
{
    public partial class User
    {
        public User()
        {
            Conversation = new HashSet<Conversation>();
            Ipblocker = new HashSet<Ipblocker>();
            LoginLog = new HashSet<LoginLog>();
            Order = new HashSet<Order>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public DateTime CreatedDatetime { get; set; }
        public DateTime UpdateDatetime { get; set; }

        public virtual ICollection<Conversation> Conversation { get; set; }
        public virtual ICollection<Ipblocker> Ipblocker { get; set; }
        public virtual ICollection<LoginLog> LoginLog { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}