// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIReact.Enitities
{
    public partial class Messages
    {
        public Guid Id { get; set; }
        public Guid ConversationId { get; set; }
        public string Message { get; set; }
        public int OrderNo { get; set; }
    }
}