// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIDAL.Entities
{
    public partial class AvailableTopping
    {
        public Guid Id { get; set; }
        public Guid MenuItemId { get; set; }
        public Guid ToppingId { get; set; }
    }
}