// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIDAL.Entities
{
    public partial class AvailableSizeV
    {
        public Guid Id { get; set; }
        public string Item { get; set; }
        public string Size { get; set; }
        public int Value { get; set; }
    }
}