// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIDAL.Entities
{
    public partial class AvailableSize
    {
        public int Id { get; set; }
        public Guid SizeId { get; set; }
        public Guid MenuItemId { get; set; }
        public int Value { get; set; }

        public virtual MenuItem MenuItem { get; set; }
        public virtual Size Size { get; set; }
    }
}