// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIDAL.Entities
{
    public partial class Conversation
    {
        public Conversation()
        {
            Message = new HashSet<Message>();
        }

        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public DateTime CreatedDatetime { get; set; }
        public DateTime UpdateDatetime { get; set; }

        public virtual User User { get; set; }
        public virtual ICollection<Message> Message { get; set; }
    }
}