// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIDAL.Entities
{
    public partial class LoginLog
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public string Ipaddress { get; set; }
        public string Device { get; set; }
        public string CountryCode { get; set; }
        public DateTime CreatedDatetime { get; set; }
        public DateTime UpdateDatetime { get; set; }
    }
}