// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenAIDAL.Entities
{
    public partial class Suger
    {
        public Suger()
        {
            AvailableSuger = new HashSet<AvailableSuger>();
            OrderDetail = new HashSet<OrderDetail>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedDatetime { get; set; }
        public DateTime UpdateDatetime { get; set; }

        public virtual ICollection<AvailableSuger> AvailableSuger { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}